// <auto-generated />
namespace TicketManagement.Migrations.Application
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fixingproblemwithdatesgettingoverridden : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixingproblemwithdatesgettingoverridden));
        
        string IMigrationMetadata.Id
        {
            get { return "201512062117216_Fixing problem with dates getting overridden"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
