// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace TicketManagement.Migrations.Application
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReReInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReReInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201512270115218_Re-Re-Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
