//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x255044462D312E350D0A25B5B5B5B50D0A312030206F626A0D0A3C3C2F547970652F436174616C6F672F50616765732032203020522F4C616E6728656E2D474229202F53747275637454726565526F6F74203434203020522F4D61726B496E666F3C3C2F4D61726B656420747275653E3E3E3E0D0A656E646F626A0D0A322030206F626A0D0A3C3C2F547970652F50616765732F436F756E7420352F4B6964735B203320302052203330203020522033322030205220333420302052203336203020525D203E3E0D0A656E646F626A0D0A332030206F626A0D0A3C3C2F547970652F506167652F506172656E742032203020522F5265736F75726365733C3C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataPopulation_File1_Content {
            get {
                return ResourceManager.GetString("DataPopulation_File1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        internal static string HomeController_Login_InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("HomeController_Login_InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem reading max text message length from the config, please see a system administrator..
        /// </summary>
        internal static string TextMessageController_Send_ErrorMaxLengthFromConfig {
            get {
                return ResourceManager.GetString("TextMessageController_Send_ErrorMaxLengthFromConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure there is a Message body..
        /// </summary>
        internal static string TextMessageController_Send_MessageBodyRequired {
            get {
                return ResourceManager.GetString("TextMessageController_Send_MessageBodyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure there is a Recipient selected..
        /// </summary>
        internal static string TextMessageController_Send_RecipientSelectionRequired {
            get {
                return ResourceManager.GetString("TextMessageController_Send_RecipientSelectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deadline is required.
        /// </summary>
        internal static string TicketsController_Create_DeadlineRequired {
            get {
                return ResourceManager.GetString("TicketsController_Create_DeadlineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deadline not in the correct format &apos;dd/mm/yyyy&apos;.
        /// </summary>
        internal static string TicketsController_Edit_DeadlineFormat {
            get {
                return ResourceManager.GetString("TicketsController_Edit_DeadlineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with the uploaded file..
        /// </summary>
        internal static string TicketsController_NewTicketLogFile_ProblemWithUploadedFile {
            get {
                return ResourceManager.GetString("TicketsController_NewTicketLogFile_ProblemWithUploadedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file type..
        /// </summary>
        internal static string TicketsController_NewTicketLogFile_UnsupportedFileTypes {
            get {
                return ResourceManager.GetString("TicketsController_NewTicketLogFile_UnsupportedFileTypes", resourceCulture);
            }
        }
    }
}
